export const persSeleccionables = [
    {
      name: "Lirena",
      surname:"Hojasanta",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/ullpaqzt6zppkskmwzwz.png",
      oro: 0,
    salud: 100,
    clase: "",
    descripcion:"Lirena Hojasanta proviene de una familia de hábiles guerreros que han dedicado sus vidas a proteger los enclaves sagrados de su religión. Su destreza en combate es incomparable. Lirena, conocida por su valentía y sentido de la justicia, se embarca en una búsqueda para preservar la armonía entre los reinos y defender la luz.",
    combate:4,
    sabiduria:2,
    ayuda:3,
    sigilo:1,
    justicia:5,
    },
  

    {
      name: "Bruster",
      surname:"Manollameante",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/qpnweeg26egvqrxwylts.png",
      oro: 0,
      salud: 100,
    clase: "",
    descripcion:"Bruster Manollameante, un erudito respetado, ha dedicado su vida al estudio de antiguos textos y misterios olvidados. Aunque su habilidad en el combate puede parecer limitada, su profunda sabiduría y habilidades curativas lo convierten en un valioso aliado en cualquier aventura. Bruster se une a la causa para compartir sus conocimientos y buscar respuestas a los enigmas del mundo.",
    combate:1,
    sabiduria:5,
    ayuda:4,
    sigilo:3,
    justicia:2,
    },
    {
      name: "Krista",
      surname:"Alaplata",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/gs78l2xqy4z7cy6tdj9e.png",
      oro: 0,
    salud: 100,
    clase: "",
    descripcion:"Krista Alaplata es una hábil sanadora y defensora de los oprimidos. Proveniente de una familia de sanadores famosos, Krista utiliza sus habilidades para traer esperanza y alivio a aquellos que sufren. Su compasión y deseo de ayudar a los demás la impulsan a unirse a la búsqueda de un mundo más justo y equitativo.",
    combate:2,
    sabiduria:3,
    ayuda:5,
    sigilo:1,
    justicia:4,
    },
    {
      name: "Furtur",
      surname:"Manosduras",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/lc9xf3fnobm7wtnymbrt.png",
      oro: 0,
      salud: 100,
    clase: "",
    descripcion:"Furtur Manosduras, un guerrero temido en la arena de combate, ha ganado renombre por su fuerza bruta y habilidades de lucha excepcionales. Aunque su reputación puede sugerir lo contrario, Furtur también posee habilidades sutiles debidas a su pasado como ratero. Su misión es usar su poder para proteger a los más vulnerables.",
    combate:5,
    sabiduria:1,
    ayuda:3,
    sigilo:4,
    justicia:2,
    },
    {
      name: "Darion",
      surname:"Muertesombra",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801517/eyijc8gkbetvbbzy2ymu.png",
      oro: 0,
    salud: 100,
    clase: "",
    descripcion:"Darion Muertesombra es un maestro del sigilo y la infiltración, con un pasado envuelto en misterio. Su astucia y habilidades para moverse en las sombras lo convierten en un espía experto. A pesar de su naturaleza reservada, Darion se une a la causa con la esperanza de desentrañar conspiraciones oscuras y restablecer la paz en la tierra.",
    combate:3,
    sabiduria:4,
    ayuda:2,
    sigilo:5,
    justicia:1,
    },
  ];

  export const medallasPersonajes={
  Lirena:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705420698/tytl5prduts1mcrmhz5w.png",
   Bruster:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705444187/p3lzvvpmzevmzfw4yl7u.png" ,
Krista:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705444187/ymenfwpypqa0bo3uqmhx.png" ,
Furtur:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705444187/ex3pvdt6amspm2bxqpt9.png" ,
Darion:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705444187/yyme20utgvc9g4zfxdct.png",



 
  }