export const persSeleccionables = [
    {
      name: "Lirena",
      surname:"Hojasanta",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/ullpaqzt6zppkskmwzwz.png",
      oro: "",
    salud: "",
    clase: "",
    descripcion:"Lirena no es una aventurera al uso, solo deja de proteger al lider de su religión para atender tareas que no son confiables a nadie mas.Todos estos años de servicio han hecho que sea bendecida directamente por su Dios, lo que le ha conferido fuerza y voluntad más allá de un ser humano corriente, además es capaz de sanar heridas leves gracias a esta bendición",
    fuerza:2,
    inteligencia:3,
    carisma:1,
    sigilo:0,
    },
  

    {
      name: "Bruster",
      surname:"Manollameante",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/qpnweeg26egvqrxwylts.png",
      oro: "",
    salud: "",
    clase: "",
    descripcion:"Quemar accidentalmente el horfanato dondo lo criaban es solo el primero de muchos tormentosos recuerdos que tiene Bruster.Desde ese día solo ha estado buscando maneras de que lo mismo que ocasionó tanto daño sirva ahora para mejorar la vida de alguien. Trabaja en conjunto con los líderes del reino para traer la paz.",
    fuerza:0,
    inteligencia:3,
    carisma:2,
    sigilo:1,
    },
    {
      name: "Krista",
      surname:"Alaplata",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/gs78l2xqy4z7cy6tdj9e.png",
      oro: "",
    salud: "",
    clase: "",
    descripcion:"Lirena no es una aventurera al uso, solo deja de proteger al lider de su religión para atender tareas que no son confiables a nadie mas.Todos estos años de servicio han hecho que sea bendecida directamente por su Dios, lo que le ha conferido fuerza y voluntad más allá de un ser humano corriente, además es capaz de sanar heridas leves gracias a esta bendición",
    fuerza:2,
    inteligencia:3,
    carisma:0,
    sigilo:0,
    },
    {
      name: "Furtur",
      surname:"Manosduras",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/lc9xf3fnobm7wtnymbrt.png",
      oro: "",
    salud: "",
    clase: "",
    descripcion:"Lirena no es una aventurera al uso, solo deja de proteger al lider de su religión para atender tareas que no son confiables a nadie mas.Todos estos años de servicio han hecho que sea bendecida directamente por su Dios, lo que le ha conferido fuerza y voluntad más allá de un ser humano corriente, además es capaz de sanar heridas leves gracias a esta bendición",
    fuerza:2,
    inteligencia:3,
    carisma:0,
    sigilo:0,
    },
    {
      name: "Darion",
      surname:"Muertesombra",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801517/eyijc8gkbetvbbzy2ymu.png",
      oro: "",
    salud: "",
    clase: "",
    descripcion:"Lirena no es una aventurera al uso, solo deja de proteger al lider de su religión para atender tareas que no son confiables a nadie mas.Todos estos años de servicio han hecho que sea bendecida directamente por su Dios, lo que le ha conferido fuerza y voluntad más allá de un ser humano corriente, además es capaz de sanar heridas leves gracias a esta bendición",
    fuerza:2,
    inteligencia:3,
    carisma:0,
    sigilo:0,
    },
  ];