export const persSeleccionables = [
    {
      name: "Lirena",
      surname:"Flechaveloz",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1705889441/mkyfvcwomcqf4dpc2jup.png",
      oro: 0,
    salud: 100,
    clase: "",
    descripcion:"Lirena Flechaveloz, una arquera de mirada fiera y corazón indomable, destaca entre la multitud como una maestra del arco y la flecha. Lirena lleva consigo el aire de alguien que ha explorado las fronteras de la tierra y desafiado a la misma naturaleza.",
    fuerza:1,
    sabiduria:2,
    carisma:3,
    sigilo:4,
    destreza:5,
    },
  

    {
      name: "Bruster",
      surname:"Manollameante",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/qpnweeg26egvqrxwylts.png",
      oro: 0,
      salud: 100,
    clase: "",
    descripcion:"Bruster Manollameante, un erudito respetado, ha dedicado su vida al estudio de antiguos textos y misterios olvidados. Aunque su habilidad en el fuerza puede parecer limitada, su profunda sabiduría y habilidades curativas lo convierten en un valioso aliado en cualquier aventura. Bruster se une a la causa para compartir sus conocimientos y buscar respuestas a los enigmas del mundo.",
    fuerza:1,
    sabiduria:5,
    carisma:4,
    sigilo:3,
    destreza:2,
    },
    {
      name: "Krista",
      surname:"Tonoalegre",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1705889236/ijkpsy151fmv2fqavgc2.png",
      oro: 0,
    salud: 100,
    clase: "",
    descripcion:"Krista Tonoalegre es una talentosa barda que ha cautivado a audiencias por todo el reino con su habilidad musical y su encantadora personalidad. Con cabellos dorados que caen en ondas suaves hasta sus hombros y ojos que destilan la chispa de la creatividad, Krista es conocida por su carisma y su capacidad para llevar la alegría a cualquier lugar al que vaya.",
    fuerza:2,
    sabiduria:3,
    carisma:5,
    sigilo:1,
    destreza:4,
    },
    {
      name: "Furtur",
      surname:"Manosduras",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801406/lc9xf3fnobm7wtnymbrt.png",
      oro: 0,
      salud: 100,
    clase: "",
    descripcion:"Furtur Manosduras, un guerrero temido en la arena de fuerza, ha ganado renombre por su fuerza bruta y habilidades de lucha excepcionales. Aunque su reputación puede sugerir lo contrario, Furtur también posee habilidades sutiles debidas a su pasado como ratero. Su misión es usar su poder para proteger a los más vulnerables.",
    fuerza:5,
    sabiduria:1,
    carisma:3,
    sigilo:4,
    destreza:2,
    },
    {
      name: "Darion",
      surname:"Muertesombra",
      img: "https://res.cloudinary.com/djfkchzyq/image/upload/v1704801517/eyijc8gkbetvbbzy2ymu.png",
      oro: 0,
    salud: 100,
    clase: "",
    descripcion:"Darion Muertesombra es un maestro del sigilo y la infiltración, con un pasado envuelto en misterio. Su astucia y habilidades para moverse en las sombras lo convierten en un espía experto. A pesar de su naturaleza reservada, Darion se une a la causa con la esperanza de desentrañar conspiraciones oscuras y restablecer la paz en la tierra.",
    fuerza:3,
    sabiduria:1,
    carisma:2,
    sigilo:5,
    destreza:4,
    },
  ];

  export const medallasPersonajes={
  Lirena:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705420698/tytl5prduts1mcrmhz5w.png",
   Bruster:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705444187/p3lzvvpmzevmzfw4yl7u.png" ,
Krista:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705444187/ymenfwpypqa0bo3uqmhx.png" ,
Furtur:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705444187/ex3pvdt6amspm2bxqpt9.png" ,
Darion:"https://res.cloudinary.com/djfkchzyq/image/upload/v1705444187/yyme20utgvc9g4zfxdct.png",



 
  }